name: Compilar APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Crear proyecto Cordova
        run: |
          cordova create app_cordova com.miApp.calendario "MiAplicacion"
          cp -r * app_cordova/www/ 2>/dev/null || true
          cd app_cordova
          cordova platform add android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Compilar APK Android
        run: |
          cd app_cordova
          cordova build android

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi-Aplicacion-APK
          path: app_cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk
